# Copyright 2025 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install node_modules
        run: npm ci

      - name: Build
        run: npm build

      - name: Test
        run: npm test

      - name: Publish
        run: pnpm publish --tag '${{ github.event.inputs.npm_tag }}' --access public --no-git-checks ${{ inputs.dry_run && '--dry-run' || ''}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
